version: "3.3"

services:
  spark:
    image: docker.io/bitnami/spark:3.1.2-debian-10-r130
    volumes:
      - .:/app_data
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '18080:8080'
  spark-worker:
    image: docker.io/bitnami/spark:3.1.2-debian-10-r130
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      
  java:
    image: openjdk:15-alpine
    volumes:
      - .:/app_data
    command: "java -jar /app_data/services-0.0.1-SNAPSHOT.jar > /app_data/java.log"
    ports:
      - '9080:8080'
      
  cass_seedprovider:
    image: cassandra:4
    ports:
      - "9042:9042"
    volumes:
      - "cass_store_seedprovider:/var/lib/cassandra"
      - .:/app_data
    environment:
      - "CASSANDRA_SEEDS=cass_seedprovider"
      - "CASSANDRA_CLUSTER_NAME=Movies Example Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cass_node_1:
    image: cassandra:4
    volumes:
      - "cass_store_1:/var/lib/cassandra"
    depends_on:
      - cass_seedprovider
    environment:
      - "CASSANDRA_SEEDS=cass_seedprovider"
      - "CASSANDRA_CLUSTER_NAME=Movies Example Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M


  cass_node_2:
    image: cassandra:4
    volumes:
      - "cass_store_2:/var/lib/cassandra"
    depends_on:
      - cass_seedprovider
    environment:
      - "CASSANDRA_SEEDS=cass_seedprovider"
      - "CASSANDRA_CLUSTER_NAME=Movies Example Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M


volumes:
  cass_store_seedprovider:
    driver: local
  cass_store_1:
    driver: local
  cass_store_2:
    driver: local
